export const styles = {
  card: {
    backgroundColor: '#ffffff',
    padding: 'clamp(0.75rem, 2vw, 1.5rem)',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    marginBottom: '1rem',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    minWidth: '800px', // Ensures table doesn't get too cramped
  },
  th: {
    padding: 'clamp(0.5rem, 1.5vw, 0.75rem) clamp(0.5rem, 1.5vw, 1rem)',
    textAlign: 'center' as const,
    verticalAlign: 'middle' as const,
    borderBottom: '2px solid #e2e8f0',
  },
  thContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
    alignItems: 'center',
  },
  thTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    fontWeight: 600,
    color: '#4a5568',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    textTransform: 'uppercase' as const,
    cursor: 'pointer' as const,
  },
  td: {
    padding: 'clamp(0.5rem, 1.5vw, 1rem)',
    color: '#2d3748',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    borderBottom: '1px solid #e2e8f0',
    textAlign: 'center' as const,
    verticalAlign: 'middle' as const,
  },
  input: {
    display: 'block',
    width: 'calc(100% - 16px)',
    padding: 'clamp(6px, 1vw, 8px)',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    border: '1px solid #cbd5e0',
    borderRadius: '4px',
    backgroundColor: '#ffffff',
  },
  select: {
    display: 'block',
    width: '100%',
    padding: 'clamp(6px, 1vw, 8px)',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    border: '1px solid #cbd5e0',
    borderRadius: '4px',
    backgroundColor: '#ffffff',
  },
  button: {
    padding: 'clamp(0.4rem, 1vw, 0.5rem) clamp(0.75rem, 2vw, 1rem)',
    backgroundColor: '#3182ce',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer' as const,
    fontWeight: 600,
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
  },
  closeButton: {
    position: 'absolute' as const,
    top: 'clamp(0.5rem, 1vw, 1rem)',
    right: 'clamp(0.5rem, 1vw, 1rem)',
    padding: '0.5rem',
    backgroundColor: '#e2e8f0',
    color: '#4a5568',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer' as const,
    fontWeight: 600,
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    lineHeight: 1,
    width: 'clamp(28px, 5vw, 32px)',
    height: 'clamp(28px, 5vw, 32px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: 'clamp(0.5rem, 2vw, 1rem)',
  },
  modalContent: {
    position: 'relative' as const,
    background: 'white',
    padding: 'clamp(1rem, 3vw, 2rem)',
    borderRadius: '12px',
    width: '100%',
    maxWidth: 'min(90vw, 900px)',
    maxHeight: '90vh',
    overflowY: 'auto' as const,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    backgroundClip: 'padding-box',
  },
  filterBar: {
    marginBottom: 'clamp(1rem, 2vw, 1.5rem)',
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  filterPill: {
    display: 'inline-flex',
    alignItems: 'center',
    background: '#e2e8f0',
    color: '#2d3748',
    padding: '0.35rem 0.75rem',
    borderRadius: '16px',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    fontWeight: 500,
  },
  sortPill: {
    display: 'inline-flex',
    alignItems: 'center',
    background: '#dbeafe',
    color: '#1e40af',
    padding: '0.35rem 0.75rem',
    borderRadius: '16px',
    fontSize: 'clamp(0.75rem, 1.5vw, 0.875rem)',
    fontWeight: 500,
  },
  filterRemoveBtn: {
    marginLeft: '0.5rem',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer' as const,
    color: '#718096',
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    padding: 0,
  },
  assigneeCount: {
    display: 'inline-block',
    backgroundColor: '#3182ce',
    color: 'white',
    borderRadius: '50%',
    width: 'clamp(20px, 4vw, 24px)',
    height: 'clamp(20px, 4vw, 24px)',
    textAlign: 'center' as const,
    lineHeight: 'clamp(20px, 4vw, 24px)',
    fontSize: 'clamp(0.7rem, 1.5vw, 0.75rem)',
    fontWeight: 600,
    cursor: 'pointer' as const,
  },
  popup: {
    position: 'fixed' as const,
    backgroundColor: '#2d3748',
    color: 'white',
    padding: 'clamp(0.4rem, 1vw, 0.5rem)',
    borderRadius: '6px',
    fontSize: 'clamp(0.7rem, 1.5vw, 0.75rem)',
    zIndex: 9999,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    maxWidth: 'min(90vw, 200px)',
    whiteSpace: 'nowrap' as const,
    pointerEvents: 'none' as const,
  },
  popupItem: {
    marginBottom: '0.25rem',
  },
  popupItemLast: {
    marginBottom: 0,
  },
};
