name: Unit Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  base-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Run unit tests (Jest)
      - name: Run Unit Tests
        run: npm run test:ci

      # Check if coverage file exists
      - name: Check Coverage File
        run: |
          if [ ! -f ./coverage/lcov.info ]; then
            echo "Coverage file not found!"
            exit 1
          fi

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
