name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # type checking
      - name: TypeScript Type Check
        run: npx tsc --noEmit

      # format checking
      - name: Run Prettier Check
        run: npm run format:check

      # lint checking
      - name: Run ESLint
        run: npm run lint
