name: Security Scan

on:
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # check dependcy vulnerability
      - name: Run npm audit
        run: npm audit --audit-level=high

      # SAST (Static Application Security Testing)
      - name: Run CodeQL Scan
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
